# Welcome to Jekyll!

## bundle exec jekyll serve      
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# phone: 555-not-a-real-number # Your phone number
# dob: 12.12.2012 # Your date of birth
image: linux.jpg
# twitter_handle: # Your twitter handle

name: Stephanie Chatagner
email:

tagline: Personal cover page # Appears on the sidebar bellow your name.
twitter_username: avoir
github_username: anthelix
address: Chatillon
linkedin_url: https://www.linkedin.com/in/stephaniechatagner/ # Your linkedin public url

title_job: Data Analyst
abstract: > # Here you should write a brief summary about yourself.
  Data Analyst enthousiasmée  par le traitement et le nettoyage des données, une expérience métier dans le secteur médical plus particulièrement en Orthopédie, Logistique Médicale et Hygiène, une affinité pour la data et le data cleansing, des projets en data engineering, des projets de data analytique.  Compétences en Python, Tableau, SQL, Linux, Pyspark
description: > # Description for site meta, used by search engines.
  Personal cover page for this test user.
title: Stephanie Chatagner's Blog

description: >- # this means to ignore newlines until "baseurl:"
  Just a blog for my code.
  
baseurl: "/anth_blog" # the subpath of your site, e.g. /blog
url: "https://anthelix.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

#permalink: /:basename

defaults:
  - scope:
      path: "_posts/news"
    values:
      type: "news"
  - scope:
      path: "_posts/work"
    values:
      type: "work"

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

# Localization
projects: Personal projects
skills: Skills
languages: Language
hobbies: Hobbies
experience: Experience
education: Education
email_text: Email
phone_text: Phone
dob_text: Date of birth
address_text: Address


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
